import = ["~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]
live_config_reload = true

[selection]
save_to_clipboard = true

[font]
size = 18.0

[font.normal]
family = "MesloLGS NF"

[scrolling]
history = 10000

[window]
decorations = "None"
dynamic_title = false

[window.position]
x = 16
y = 24

[keyboard]
bindings = [
    { key = "Space", mods = "Control|Shift", action = "ToggleViMode" },
]