[package]
name = "bash_listner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.9.7"
evdev-rs = "0.3.1"
input = "0.9.0"
libc = "0.2.153"
