#!/usr/bin/env sh

# Set layout to bsp (Binary Space Partitioning)
# yabai -m config layout bsp

# Define window gaps and padding
# yabai -m config top_padding    10
# yabai -m config bottom_padding 10
# yabai -m config left_padding   10
# yabai -m config right_padding  10
# yabai -m config window_gap     10

# Enable window border
# yabai -m config window_border  on
yabai -m config window_border_width 3
yabai -m config active_window_border_color 0xff5c7cfa
yabai -m config normal_window_border_color 0xff505050
yabai -m config window_shadow off
